### ISSUE TITLE
Unable to install

### ISSUE THREAD

**Issue by eamonndo1993** [CICM/CicmTools#1]
Hi there

I've tried to install this on Max 7 (using a mac running OSX Sierra). I've tried copying it into packages folder within documents, and also within the public folder. Is there something I'm missing?

Thanks

Eamonn

**Comment by eliottparis** [comment]
Hi,

To use the CicmTools in Max:
- download the Max package (in your case => [CicmTools-2.1-Mac.zip](https://github.com/CICM/CicmTools/releases/download/v2.1/CicmTools-2.1-Mac.zip))
- put this folder into the `Documents/Max 7/Packages` directory.

You should then be able to instantiate an `ambicube~` / `vbapan~` / or `ambicube~` object in Max.

Let me know if you still have an issue.
Cheers!
